export interface Input {
  criteria: number;
  button: number;
  type: number;
  amount: number;
}

export interface Separator {
  index: number;
  msg?: string;
  img?: number;
}

export interface Game {
  name: string;
  image: number;
  critname: string[];
  critweight: number[];
  inputs: Input[];
  separators?: Separator[];
}

const inputDefault: Input = {
  criteria: 0,
  button: 1,
  type: 0,
  amount: 1,
};

function fillPair(
  a: Input,
  afill: number,
  b: Input,
  bfill: number,
  n: number,
): Input[] {
  const array: Input[] = [];
  for (let i = 0; i < n * 2; i++) {
    if (i % 2 === 0) {
      array.push(...Array(afill).fill(a));
    } else {
      array.push(...Array(bfill).fill(b));
    }
  }
  return array;
}

export const gameData: Game[] = [
  { // Karate Man
    name: "Karate Man",
    image: 0,
    critname: ["Single Punch", "Triple Punch"],
    critweight: [65, 25, 10],
    inputs: [
      ...Array(13).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
    ],
    separators: [{ index: 7 }],
  },
  { // Air Rally
    name: "Air Rally",
    image: 2,
    critname: ["Normal Shot", "Long Shot"],
    critweight: [70, 20, 10],
    inputs: [
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        6,
        2,
      ),
      { ...inputDefault, criteria: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
    ],
  },
  { // Catchy Tune
    name: "Catchy Tune",
    image: 3,
    critname: ["Orange", "Pineapple"],
    critweight: [40, 45, 15],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 1 },
        1,
        4,
      ),
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 2, button: 3 },
      { ...inputDefault, criteria: 2, button: 1 },
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 1, button: 1 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 1 },
        1,
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
    ],
  },
  { // Rhythm Tweezers
    name: "Rhythm Tweezers",
    image: 4,
    critname: ["Short Hair"],
    critweight: [85, 15],
    inputs: [
      ...Array(39).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
    ],
    separators: [
      { index: 4 },
      { index: 8 },
      { index: 13 },
      { index: 18 },
      { index: 24 },
      { index: 28 },
      { index: 33 },
      { index: 39 },
      { index: 43 },
    ],
  },
  { // Figure Fighter
    name: "Figure Fighter",
    image: 6,
    critname: ["Single Punch", "Double Punch"],
    critweight: [25, 60, 15],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        4,
        { ...inputDefault, criteria: 0 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
    ],
  },
  { // The Clappy Trio
    name: "The Clappy Trio",
    image: 8,
    critname: ["Main", "Fast"],
    critweight: [50, 35, 15],
    inputs: [
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Shoot-'em-up
    name: "Shoot-'em-up",
    image: 9,
    critname: ["Main", "Fast"],
    critweight: [45, 45, 10],
    inputs: [
      ...Array(17).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...Array(20).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
    ],
    separators: [
      { index: 2 },
      { index: 4 },
      { index: 6 },
      { index: 8 },
      { index: 11 },
      { index: 14 },
      { index: 17 },
      { index: 19 },
      { index: 23 },
      { index: 27 },
      { index: 31 },
      { index: 33 },
      { index: 38 },
      { index: 43 },
      { index: 48 },
      { index: 53 },
    ],
  },
  { // Micro-Row
    name: "Micro-Row",
    image: 10,
    critname: ["Single March", "Triple March"],
    critweight: [45, 45, 10],
    inputs: [
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        3,
        3,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
    ],
  },
  { // First Contact
    name: "First Contact",
    image: 11,
    critname: ["Main", "Pause", "Pork Rice Bowls"],
    critweight: [60, 15, 15, 10],
    inputs: [
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3 },
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      ...Array(5).fill({ ...inputDefault, criteria: 2 }),
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
    ],
    separators: [
      { index: 4 },
      { index: 8 },
      { index: 12 },
      { index: 13 },
      { index: 18 },
      { index: 22 },
      { index: 25 },
      { index: 26 },
      { index: 28 },
      { index: 33 },
      { index: 35 },
      { index: 40 },
      { index: 44 },
      { index: 47 },
      { index: 49 },
      { index: 54 },
    ],
  },
  { // Bunny Hop
    name: "Bunny Hop",
    image: 12,
    critname: ["Main", "Rest"],
    critweight: [70, 20, 10],
    inputs: [
      ...Array(37).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(20).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(23).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
    ],
    separators: [
      { index: 37, msg: "4-rest" },
      { index: 58, msg: "4-rest" },
      { index: 71, msg: "4-rest" },
      { index: 78, msg: "2-rest" },
      { index: 95, msg: "8-rest" },
      { index: 104, msg: "8-rest" },
      { index: 111, msg: "2-rest" },
    ],
  },
  { // Exhibition Match
    name: "Exhibition Match",
    image: 14,
    critname: ["Main", "Silent"],
    critweight: [60, 20, 20],
    inputs: [
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
    ],
  },
  { // Sneaky Spirits
    name: "Sneaky Spirits",
    image: 16,
    critname: ["Main", "Slow"],
    critweight: [50, 30, 20],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
    ],
  },
  { // Rhythm Rally
    name: "Rhythm Rally",
    image: 17,
    critname: ["Normal Swing", "Long Swing"],
    critweight: [70, 16, 14],
    inputs: [
      { ...inputDefault, criteria: 1 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Flipper-Flop
    name: "Flipper-Flop",
    image: 18,
    critname: ["Flip", "Flipper-Roll"],
    critweight: [60, 30, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        15,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        2,
      ),
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 2 }),
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 2 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1, button: 2 },
        2,
        2,
      ),
    ],
  },
  { // Power Calligraphy
    name: "Power Calligraphy",
    image: 20,
    critname: ["Main", "Chikara", "Kokoro", "Face"],
    critweight: [30, 25, 25, 10, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 4 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 3 },
    ],
  },
  { // Spaceball
    name: "Spaceball",
    image: 24,
    critname: ["Normal Shot", "High Shot"],
    critweight: [55, 35, 10],
    inputs: [
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 1 },
    ],
  },
  { // Dog Ninja
    name: "Dog Ninja",
    image: 25,
    critname: ["Single Slice", "Double Slice"],
    critweight: [52, 40, 8],
    inputs: [
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        10,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
    ],
  },
  { // Hole in One
    name: "Hole in One",
    image: 26,
    critname: ["Monkey", "Mandrill"],
    critweight: [60, 30, 10],
    inputs: [
      ...Array(17).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        1,
        3,
      ),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
    ],
  },
  { // Sumo Brothers
    name: "Sumo Brothers",
    image: 27,
    critname: ["Slap", "Stomp", "Pose"],
    critweight: [35, 35, 20, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        8,
        { ...inputDefault, criteria: 0 },
        8,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2, button: 2 },
      { ...inputDefault, criteria: 3, button: 2 },
      ...Array(16).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(16).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2, button: 2 },
    ],
  },
  { // Lush Remix
    name: "Lush Remix",
    image: 28,
    critname: ["Normal", "Keep the Beat"],
    critweight: [46, 44, 10],
    inputs: [
      ...Array(21).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(13).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(12).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
    ],
    separators: [
      { index: 0, img: 24 },
      { index: 5, img: 25 },
      { index: 11, img: 24 },
      { index: 15, img: 25 },
      { index: 21, img: 27 },
      { index: 22, img: 26 },
      { index: 24, img: 24 },
      { index: 26, img: 26 },
      { index: 28, img: 24 },
      { index: 30, img: 25 },
      { index: 35, img: 27 },
      { index: 49, img: 24 },
      { index: 54, img: 27 },
      { index: 61, img: 26 },
      { index: 65, img: 24 },
    ],
  },
  { // Karate Man Returns!
    name: "Karate Man Returns!",
    image: 29,
    critname: ["Single Punch", "Triple Punch"],
    critweight: [65, 25, 10],
    inputs: [
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        10,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      { ...inputDefault, criteria: 2 },
    ],
    separators: [
      { index: 5 },
      { index: 13 },
    ],
  },
  { // Air Rally 2
    name: "Air Rally 2",
    image: 31,
    critname: ["Normal Shot", "Far Shot", "Long Shot"],
    critweight: [44, 20, 30, 6],
    inputs: [
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(16).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        2,
        3,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(5).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 3 },
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      ...Array(8).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Catchy Tune 2
    name: "Catchy Tune 2",
    image: 32,
    critname: ["Orange", "Pineapple"],
    critweight: [45, 40, 15],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 1 },
        1,
        3,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 1, button: 1 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 1 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 1 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 2, button: 3 },
      { ...inputDefault, criteria: 2, button: 1 },
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 1 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 0, button: 3 },
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 1, button: 1 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 0, button: 1 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 1, button: 1 },
    ],
  },
  { // Figure Fighter 2
    name: "Figure Fighter 2",
    image: 36,
    critname: ["Single Punch", "Triple Punch", "Double Punch"],
    critweight: [30, 30, 30, 10],
    inputs: [
      ...Array(6).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        3,
        4,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(6).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        2,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
    ],
  },
  { // The Clappy Trio 2
    name: "The Clappy Trio 2",
    image: 39,
    critname: ["Main", "Fast"],
    critweight: [50, 36, 14],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
    ],
  },
  { // Shoot-'em-up 2
    name: "Shoot-'em-up 2",
    image: 40,
    critname: ["Main", "Fast"],
    critweight: [50, 40, 10],
    inputs: [
      ...Array(35).fill({ ...inputDefault, criteria: 0 }),
      ...Array(8).fill({ ...inputDefault, criteria: 1 }),
      ...Array(23).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2 }),
      ...Array(31).fill({ ...inputDefault, criteria: 1 }),
      ...Array(23).fill({ ...inputDefault, criteria: 0 }),
    ],
    separators: [
      { index: 4 },
      { index: 8 },
      { index: 12 },
      { index: 14 },
      { index: 18 },
      { index: 22 },
      { index: 26 },
      { index: 30 },
      { index: 35 },
      { index: 43 },
      { index: 48 },
      { index: 54 },
      { index: 58 },
      { index: 62 },
      { index: 66 },
      { index: 70 },
      { index: 78 },
      { index: 86 },
      { index: 94 },
      { index: 101 },
      { index: 105 },
      { index: 110 },
      { index: 115 },
      { index: 121 },
    ],
  },
  { // Micro-Row 2
    name: "Micro-Row 2",
    image: 41,
    critname: ["Single March", "Triple March"],
    critweight: [40, 46, 14],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        14,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1 },
        3,
        3,
      ),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        3,
        { ...inputDefault, criteria: 0 },
        2,
        3,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        4,
        { ...inputDefault, criteria: 1 },
        6,
        2,
      ),
    ],
  },
  { // Second Contact
    name: "Second Contact",
    image: 42,
    critname: ["Main", "Pause", "Fast"],
    critweight: [40, 10, 40, 10],
    inputs: [
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3 },
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      ...Array(7).fill({ ...inputDefault, criteria: 2 }),
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      ...Array(11).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(5).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
    ],
    separators: [
      { index: 5 },
      { index: 9 },
      { index: 14 },
      { index: 15 },
      { index: 20 },
      { index: 24 },
      { index: 29 },
      { index: 30 },
      { index: 34 },
      { index: 38 },
      { index: 42 },
      { index: 49 },
      { index: 53 },
      { index: 55 },
      { index: 57 },
      { index: 61 },
      { index: 67 },
      { index: 72 },
      { index: 74 },
      { index: 79 },
      { index: 85 },
    ],
  },
  { // Citrus Remix
    name: "Citrus Remix",
    image: 43,
    critname: ["Main", "Keep the Beat", "Repeat"],
    critweight: [25, 25, 40, 10],
    inputs: [
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        5,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(5).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        4,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 0 },
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
    ],
    separators: [
      { index: 0, img: 41 },
      { index: 4, img: 39 },
      { index: 5, img: 41 },
      { index: 10, img: 39 },
      { index: 12, img: 41 },
      { index: 17, img: 39 },
      { index: 19, img: 40 },
      { index: 24, img: 42 },
      { index: 28, img: 41 },
      { index: 34, img: 42 },
      { index: 39, img: 41 },
      { index: 45, img: 40 },
      { index: 49, img: 39 },
      { index: 51, img: 40 },
      { index: 55, img: 39 },
      { index: 57, img: 40 },
      { index: 59, img: 39 },
      { index: 60, img: 41 },
      { index: 66, img: 42 },
    ],
  },
  { // Working Dough
    name: "Working Dough",
    image: 46,
    critname: ["Small Ball", "Big Ball"],
    critweight: [52, 40, 8],
    inputs: [
      ...Array(24).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1, button: 2 },
        2,
        2,
      ),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        7,
        2,
      ),
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 2 }),
      ...Array(18).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1, button: 2 }),
      { ...inputDefault, criteria: 2 },
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
    ],
    separators: [
      { index: 3 },
      { index: 9 },
      { index: 13 },
      { index: 17 },
      { index: 20 },
      { index: 25 },
      { index: 29 },
      { index: 35 },
      { index: 38 },
      { index: 43 },
      { index: 47 },
      { index: 51 },
      { index: 53 },
      { index: 55 },
      { index: 58 },
      { index: 63 },
      { index: 74 },
      { index: 82 },
      { index: 90 },
      { index: 102 },
      { index: 104 },
      { index: 106 },
      { index: 110 },
      { index: 113 },
      { index: 114 },
      { index: 117 },
      { index: 120 },
    ],
  },
  { // Sneaky Spirits 2
    name: "Sneaky Spirits 2",
    image: 49,
    critname: ["Main", "Quiet", "Slow"],
    critweight: [32, 24, 24, 20],
    inputs: [
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 3 },
      { ...inputDefault, criteria: 0 },
    ],
  },
  { // Rhythm Rally 2
    name: "Rhythm Rally 2",
    image: 50,
    critname: ["Normal Swing", "Fast Swing", "Long Swing"],
    critweight: [40, 32, 20, 8],
    inputs: [
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 3 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Flipper-Flop 2
    name: "Flipper-Flop 2",
    image: 51,
    critname: ["Flip", "Triple Flip", "Flipper-Roll"],
    critweight: [30, 30, 30, 10],
    inputs: [
      ...Array(10).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(10).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(10).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(10).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(5).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(7).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(8).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(9).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(10).fill({ ...inputDefault, criteria: 2, button: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        3,
        3,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Tap Trial
    name: "Tap Trial",
    image: 54,
    critname: ["Single Tap", "Double Tap", "Triple Tap", "Jump Tap"],
    critweight: [25, 25, 25, 17, 8],
    inputs: [
      { ...inputDefault, criteria: 3 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 0 },
        2,
        4,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 0 },
        3,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 3 },
        2,
        3,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 4 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3 },
    ],
  },
  { // Ringside
    name: "Ringside",
    image: 56,
    critname: ["Speak", "Flex", "Pose"],
    critweight: [23, 29, 40, 8],
    inputs: [
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 2, button: 2 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 2, button: 2 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2, button: 2 },
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 2, button: 2 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 2, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2, button: 2 },
      { ...inputDefault, criteria: 3, button: 2 },
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 2, button: 2 }),
    ],
  },
  { // Ninja Bodyguard
    name: "Ninja Bodyguard",
    image: 59,
    critname: ["Main"],
    critweight: [70, 30],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 0, button: 3 },
        1,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 0, button: 3 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0 },
    ],
    separators: [
      { index: 1 },
      { index: 3 },
      { index: 4 },
      { index: 7 },
      { index: 8 },
      { index: 11 },
      { index: 12 },
      { index: 16 },
    ],
  },
  { // Freeze Frame
    name: "Freeze Frame",
    image: 60,
    critname: ["Triple Car", "Double Car", "Fast Car"],
    critweight: [30, 20, 40, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 2 },
        2,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Launch Party
    name: "Launch Party",
    image: 61,
    critname: ["Act 1", "Act 2"],
    critweight: [40, 52, 8],
    inputs: [
      ...Array(20).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(20).fill({ ...inputDefault, criteria: 1 }),
    ],
  },
  { // Marching Orders
    name: "Marching Orders",
    image: 63,
    critname: ["March", "Halt", "Turn"],
    critweight: [40, 25, 25, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        11,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 2, button: 3 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      { ...inputDefault, criteria: 2, button: 3 },
      ...Array(15).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 2, button: 3 }),
      ...Array(18).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Munchy Monk
    name: "Munchy Monk",
    image: 64,
    critname: ["Eat One", "Eat Two", "Eat Three"],
    critweight: [30, 30, 30, 10],
    inputs: [
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 0 },
        7,
        3,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 0 },
        1,
        4,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 3 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 2 },
        3,
        3,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
    ],
  },
  { // See-Saw
    name: "See-Saw",
    image: 65,
    critname: ["Main", "High Jump"],
    critweight: [40, 50, 10],
    inputs: [
      ...Array(10).fill({ ...inputDefault, criteria: 0 }),
      ...Array(8).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 1 },
      ...Array(20).fill({ ...inputDefault, criteria: 0 }),
      ...Array(15).fill({ ...inputDefault, criteria: 1 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Blue Bear
    name: "Blue Bear",
    image: 66,
    critname: ["Donut", "Cake"],
    critweight: [35, 40, 25],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 1, button: 3 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1, button: 3 },
        3,
        2,
      ),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(6).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 2, button: 3 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 1, button: 3 },
    ],
  },
  { // Space Dance
    name: "Space Dance",
    image: 67,
    critname: ["Pose", "Squat", "Punch"],
    critweight: [45, 25, 25, 10],
    inputs: [
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 2 },
      ...Array(3).fill({ ...inputDefault, criteria: 0, button: 3 }),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 3 },
        5,
        2,
      ),
      { ...inputDefault, criteria: 0, button: 3 },
      ...Array(4).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0, button: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0, button: 3 }),
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 3 },
      ...Array(3).fill({ ...inputDefault, criteria: 1, button: 3 }),
      { ...inputDefault, criteria: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0, button: 3 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Lockstep
    name: "Lockstep",
    image: 68,
    critname: ["Onbeat", "Offbeat", "Switch"],
    critweight: [20, 34, 40, 6],
    inputs: [
      ...Array(15).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(15).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(13).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(15).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(7).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        3,
        { ...inputDefault, criteria: 2 },
        6,
        3,
      ),
      ...Array(7).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 3 },
      { ...inputDefault, criteria: 2 },
      ...Array(15).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(15).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(30).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // The Snappy Trio
    name: "The Snappy Trio",
    image: 71,
    critname: ["Main", "Offbeat"],
    critweight: [70, 10, 20],
    inputs: [
      ...Array(21).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(13).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Figure Fighter 3
    name: "Figure Fighter 3",
    image: 73,
    critname: ["Single Punch", "Triple Punch", "Double Punch"],
    critweight: [18, 35, 37, 10],
    inputs: [
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        2,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        2,
        { ...inputDefault, criteria: 0 },
        4,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        2,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 2 },
        10,
        { ...inputDefault, criteria: 1 },
        3,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
    ],
  },
  { // Tap Trial 2
    name: "Tap Trial 2",
    image: 76,
    critname: ["Single Tap", "Double Tap", "Triple Tap", "Jump Tap"],
    critweight: [37, 10, 28, 15, 10],
    inputs: [
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 3 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 3 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 4 }),
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 3 }),
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 3 },
    ],
  },
  { // Hole in One 2
    name: "Hole in One 2",
    image: 78,
    critname: ["Monkey", "Mandrill"],
    critweight: [50, 40, 10],
    inputs: [
      { ...inputDefault, criteria: 1 },
      ...Array(9).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        3,
        3,
      ),
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        7,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        7,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        1,
        { ...inputDefault, criteria: 0 },
        3,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
    ],
  },
  { // Cosmic Dance
    name: "Cosmic Dance",
    image: 81,
    critname: ["Pose", "Squat", "Punch"],
    critweight: [45, 30, 15, 10],
    inputs: [
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 0, button: 3 }),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 3 },
        1,
        { ...inputDefault, criteria: 0, button: 3 },
        3,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 0, button: 3 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(6).fill({ ...inputDefault, criteria: 0, button: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 3 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0, button: 3 }),
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 3 },
      { ...inputDefault, criteria: 0, button: 3 },
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 3 },
        2,
        { ...inputDefault, criteria: 2 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0, button: 3 },
      { ...inputDefault, criteria: 1, button: 3 },
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Cosmic Rhythm Rally
    name: "Cosmic Rhythm Rally",
    image: 82,
    critname: ["Normal Swing", "Fast Swing", "Long Swing"],
    critweight: [40, 36, 14, 10],
    inputs: [
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 3 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Working Dough 2
    name: "Working Dough 2",
    image: 83,
    critname: ["Small Ball", "Big Ball"],
    critweight: [45, 40, 15],
    inputs: [
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1, button: 2 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        4,
      ),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        3,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(4).fill({ ...inputDefault, criteria: 1, button: 2 }),
      { ...inputDefault, criteria: 2 },
      ...Array(7).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1, button: 2 },
    ],
    separators: [
      { index: 2 },
      { index: 4 },
      { index: 6 },
      { index: 8 },
      { index: 9 },
      { index: 12 },
      { index: 14 },
      { index: 16 },
      { index: 19 },
      { index: 20 },
      { index: 23 },
      { index: 25 },
      { index: 27 },
      { index: 28 },
      { index: 30 },
      { index: 34 },
      { index: 37 },
      { index: 40 },
      { index: 44 },
      { index: 49 },
      { index: 51 },
      { index: 53 },
      { index: 57 },
      { index: 60 },
      { index: 61 },
      { index: 63 },
      { index: 65 },
    ],
  },
  { // Double Date
    name: "Double Date",
    image: 93,
    critname: ["Soccer Ball", "Basketball", "Rugby Ball"],
    critweight: [40, 30, 22, 8],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        1,
        2,
      ),
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 3 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Catch of the Day
    name: "Catch of the Day",
    image: 94,
    critname: ["Quicknibble", "Pausegill", "Threefish"],
    critweight: [45, 20, 20, 15],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        6,
        { ...inputDefault, criteria: 2 },
        1,
        2,
      ),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 3 },
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 2 },
    ],
  },
  { // Fork Lifter
    name: "Fork Lifter",
    image: 95,
    critname: ["Main", "Fast"],
    critweight: [40, 45, 15],
    inputs: [
      ...Array(8).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        5,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(16).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        1,
        { ...inputDefault, criteria: 1 },
        2,
        4,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        2,
        { ...inputDefault, criteria: 0 },
        1,
        2,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Love Rap
    name: "Love Rap",
    image: 96,
    critname: ["Main", "All about you!", "Fo' sho'!"],
    critweight: [30, 30, 30, 10],
    inputs: [
      ...Array(14).fill({ ...inputDefault, criteria: 0 }),
      ...Array(6).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 0 },
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      { ...inputDefault, criteria: 3 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
    ],
  },
  { // Bossa Nova
    name: "Bossa Nova",
    image: 97,
    critname: ["Left Side", "Right Side"],
    critweight: [35, 55, 10],
    inputs: [
      ...Array(3).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        3,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        4,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...Array(13).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(7).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 1 },
        5,
        { ...inputDefault, criteria: 0 },
        2,
        2,
      ),
      ...Array(3).fill({ ...inputDefault, criteria: 1 }),
      ...Array(2).fill({ ...inputDefault, criteria: 0 }),
      ...Array(3).fill({ ...inputDefault, criteria: 2 }),
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        2,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 1 },
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
    ],
  },
  { // Board Meeting
    name: "Board Meeting",
    image: 99,
    critname: ["Single", "All"],
    critweight: [56, 30, 14],
    inputs: [
      { ...inputDefault, criteria: 1 },
      ...Array(6).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
      { ...inputDefault, criteria: 2 },
      ...Array(5).fill({ ...inputDefault, criteria: 0 }),
      { ...inputDefault, criteria: 1 },
    ],
  },
  { // Packing Pests
    name: "Packing Pests",
    image: 101,
    critname: ["Main", "Double Up"],
    critweight: [35, 55, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        3,
      ),
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0, button: 2 },
        1,
        { ...inputDefault, criteria: 0 },
        1,
        2,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        { ...inputDefault, criteria: 1 },
        2,
        3,
      ),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      { ...inputDefault, criteria: 1, button: 2 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0, button: 2 },
      { ...inputDefault, criteria: 0 },
      ...fillPair(
        { ...inputDefault, criteria: 1, button: 2 },
        1,
        { ...inputDefault, criteria: 1 },
        2,
        2,
      ),
      { ...inputDefault, criteria: 2, button: 2 },
    ],
  },
  { // Monkey Watch
    name: "Monkey Watch",
    image: 102,
    critname: ["High-five", "Ooki oo!"],
    critweight: [50, 40, 10],
    inputs: [
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        7,
        { ...inputDefault, criteria: 1 },
        2,
        4,
      ),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        2,
        7,
      ),
      ...Array(4).fill({ ...inputDefault, criteria: 0 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        3,
        { ...inputDefault, criteria: 1 },
        2,
        4,
      ),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 1 }),
      { ...inputDefault, criteria: 0 },
      ...Array(2).fill({ ...inputDefault, criteria: 2 }),
      ...fillPair(
        { ...inputDefault, criteria: 0 },
        7,
        { ...inputDefault, criteria: 1 },
        2,
        4,
      ),
      ...Array(12).fill({ ...inputDefault, criteria: 0 }),
    ],
    separators: [
      { index: 80 },
      { index: 101 },
    ],
  },
];
/*
{ ...inputDefault, criteria: 0 },

...Array(2).fill({ ...inputDefault, criteria: 0 }),

...fillPair({ ...inputDefault, criteria: 0 },1,
                  { ...inputDefault, criteria: 0 },1,
        2),

{ //
    name: "",
    critname: ["",""],
    critweight: [,,],
    inputs: [

    ],
  },
*/
